url: "https://kinyugo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kinyugo Maina" # the name of your site, e.g. ACME Corp.
author_name: "Kinyugo Maina"
author_title: "ML Engineer & Researcher"
author_email: kinyugomaina@gmail.com
author_biography: >
  Hello, I’m Kinyugo Maina, a Machine Learning Engineer and Researcher specializing in Generative AI. With a background in Computer Science, I create AI-driven solutions across virtual try-on, music synthesis, and virtual product photography, leveraging deep learning to tackle real-world challenges. I'm passionate about advancing Generative AI and contributing to this growing field.

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

postcss:
  cache: false

paginate: 6
paginate_path: blog/page:num/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: katex

